@startuml

title "Besu - Plugin"
scale 1.2


BesuContext <|.. BesuPluginContextImpl
PluginVersionsProvider <|.. BesuPluginContextImpl

interface PluginVersionsProvider {
    +getPluginVersions()
}

interface BesuContext {
    +getService()
}

class BesuPluginContextImpl {
    -BesuService: Map
    -BesuPlugin: List
    +addService()
    +getService()
    +registerPlugins()
    +startPlugins()
    +stopPlugins()
}

interface BesuPlugin {
    +getName()
    +register()
    +start()
    +reloadConfiguration()
    +stop()
}

class RocksDBCLIOptions { 
    +create()
    +fromConfig()
}

interface KeyValueStorageFactory {
    +getName()
    +create()
    +isSegmentIsolationSupported()
}

interface PrivacyKeyValueStorageFactory {
    +getVersion()
}
KeyValueStorageFactory <|.. PrivacyKeyValueStorageFactory

class RocksDBKeyValueStorageFactory {
    -KeyValueStorage
    -storagePath()
    -readDatabaseVersion()
}
KeyValueStorageFactory <|.. RocksDBKeyValueStorageFactory

class RocksDBKeyValuePrivacyStorageFactory {
    -RocksDBKeyValueStorageFactory
}
RocksDBKeyValuePrivacyStorageFactory o-- RocksDBKeyValueStorageFactory
PrivacyKeyValueStorageFactory <|.. RocksDBKeyValuePrivacyStorageFactory

class RocksDBPlugin {
    -RocksDBCLIOptions
    -BesuContext
    -RocksDBKeyValueStorageFactory
    -RocksDBKeyValuePrivacyStorageFactory
    -createFactoriesAndRegisterWithStorageService()
}

class MemoryKeyValueStorageFactory {
    -name: String
    -storageMap: Map<SegmentIdentifier, InMemoryKeyValueStorage>
}
KeyValueStorageFactory <|.. MemoryKeyValueStorageFactory

class InMemoryStoragePlugin {
    -BesuContext
    -MemoryKeyValueStorageFactory
}

interface BesuService {
}

BesuPlugin <|.. RocksDBPlugin
BesuPlugin <|.. InMemoryStoragePlugin

RocksDBCLIOptions ..* RocksDBPlugin
RocksDBKeyValueStorageFactory ..* RocksDBPlugin
RocksDBKeyValuePrivacyStorageFactory ..* RocksDBPlugin

MemoryKeyValueStorageFactory ..* InMemoryStoragePlugin


RocksDBPlugin o-- BesuPluginContextImpl
InMemoryStoragePlugin o-- BesuPluginContextImpl


class SecurityModuleServiceImpl {
    -SecurityModule:Map
}

SecurityModuleService ..|> BesuService
SecurityModuleServiceImpl --|> SecurityModuleService
BesuPluginContextImpl o-- SecurityModuleServiceImpl

interface StorageService {
    +registerKeyValueStorage()
    +getAllSegmentIdentifiers()
    +getByName()
}

class StorageServiceImpl {
    -SegmentIdentifier:List
    -KeyValueStorageFactory:Map
}

StorageService ..|> BesuService
StorageServiceImpl ..|> StorageService
BesuPluginContextImpl o-- StorageServiceImpl
RocksDBKeyValueStorageFactory --o StorageServiceImpl
RocksDBKeyValuePrivacyStorageFactory --o StorageServiceImpl


interface BesuEvents {
    +addBlockPropagatedListener()
    +addBlockAddedListener()
    +addBlockReorgListener()
    +addTransactionAddedListener()
    +addTransactionDroppedListener()
    +addSyncStatusListener()
    +addLogListener()
    +remove()
}
class BesuEventsImpl {
    -Blockchain
    -BlockBroadcaster
    -TransactionPool
    -SyncState
}
BesuEvents ..|> BesuService
BesuEventsImpl ..|> BesuEvents
BesuPluginContextImpl o-- BesuEventsImpl



interface PoAMetricsService {
    +getValidatorsForLatestBlock()
    +getProposerOfBlock()
}
PoAMetricsService ..|> BesuService
interface PoaQueryService {
    +getValidatorsForLatestBlock()
    +getProposerOfBlock()
    +getLocalSignerAddress()
}
PoaQueryService ..|> BesuService
class PoaQueryServiceImpl {
    -BlockInterface
    -Blockchain
    -NodeKey
}
PoaQueryServiceImpl ..|> PoAMetricsService
PoaQueryServiceImpl ..|> PoaQueryService

interface IbftQueryService {
    +getRoundNumberFrom()
    +getSignersFrom()
}
IbftQueryService ..|> PoaQueryService

class IbftQueryServiceImpl {
    -BftBlockInterface
}
IbftQueryServiceImpl ..|> IbftQueryService
IbftQueryServiceImpl --|> PoaQueryServiceImpl
BesuPluginContextImpl o-- IbftQueryServiceImpl

interface BftQueryService {
    +getRoundNumberFrom()
    +getSignersFrom()
    +getConsensusMechanismName()
}
class BftQueryServiceImpl {
    -ValidatorProvider
    -BftBlockInterface
    -consensusMechanismName:String
}
BftQueryService ..|> PoaQueryService
BftQueryServiceImpl ..|> BftQueryService
BftQueryServiceImpl --|> PoaQueryServiceImpl
BesuPluginContextImpl o-- BftQueryServiceImpl

@enduml